version: '3'

services:
  go:
    build:
      context: .
      dockerfile: ${DIST_PREFIX}/go/Dockerfile
  java:
    build:
      context: .
      dockerfile: ${DIST_PREFIX}/java/Dockerfile
  php:
    build: 
      context: .
      dockerfile: ${DIST_PREFIX}/php/Dockerfile
  python:
    build: 
      context: .
      dockerfile: ${DIST_PREFIX}/python/Dockerfile
  ruby:
    build: 
      context: .
      dockerfile: ${DIST_PREFIX}/ruby/Dockerfile
  perl:
    build: 
      context: .
      dockerfile: ${DIST_PREFIX}/perl/Dockerfile
  node:
    build: 
      context: .
      dockerfile: ${DIST_PREFIX}/node/Dockerfile
    

