version: '3'

services:
  go:
    build:
      context: .
      dockerfile: ${DIST_PREFIX}/go/Dockerfile
  java:
    build:
      context: .
      dockerfile: ${DIST_PREFIX}/java/Dockerfile
  php:
    build: 
      context: .
      dockerfile: ${DIST_PREFIX}/php/Dockerfile
  python:
    build: 
      context: .
      dockerfile: ${DIST_PREFIX}/python/Dockerfile
  ruby:
    build: 
      context: .
      dockerfile: ${DIST_PREFIX}/ruby/Dockerfile
  perl:
    build: 
      context: .
      dockerfile: ${DIST_PREFIX}/perl/Dockerfile
  node:
    build: 
      context: .
      dockerfile: ${DIST_PREFIX}/node/Dockerfile
    ports:
      - "3000:3000"
  rails:
    build: 
      context: .
      dockerfile: ${DIST_PREFIX}/rails/Dockerfile
    ports:
      - "3000:3000"
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'mysql'
      APP_DATABASE: 'app_development'
      APP_DATABASE_USER: 'app'
      APP_DATABASE_PASSWORD: 'development'
    depends_on:
      - mysql
  mysql:
    build: 
      context: .
      dockerfile: ${DIST_PREFIX}/mysql/Dockerfile
    container_name: 'mysql'
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'app_development'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'development'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
  php-apache:
    build: 
      context: .
      dockerfile: ${DIST_PREFIX}/php-apache/Dockerfile
    ports:
      - '8001:8001'
  spring:
    build: 
      context: .
      dockerfile: ${DIST_PREFIX}/spring/Dockerfile
    ports:
      - '8080:8080'
